apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: SPRING_APPLICATION_NAME
              value: "inno-api-gateway"
            - name: SERVER_PORT
              value: "8080"
            - name: TOKEN_PREFIX
              value: "Bearer"
            - name: AUTH_WHITELIST_PATHS
              value: "/auth/login,/auth/register,/auth/refresh"
            - name: HEADER_USER_ID
              value: "X-User-Id"
            - name: CONTENT_TYPE_JSON
              value: "application/json"
            - name: AUTH_SERVICE_URI
              value: "http://auth-service:8081"
            - name: USER_SERVICE_URI
              value: "http://user-service:8082"
            - name: ORDER_SERVICE_URI
              value: "http://order-service:8086"
            - name: PAYMENT_SERVICE_URI
              value: "http://payment-service:8087"
            - name: JWT_SECRET
              value: "MySuperSecretKeyForJWTMySuperSecretKeyForJWT"
            - name: JWT_EXPIRATION
              value: "3600000"
            - name: JWT_HEADER
              value: "Authorization"
            - name: JWT_TOKEN_PREFIX
              value: "Bearer"
            - name: JWT_ROLE_PREFIX
              value: "ROLE_"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: RANDOM_API_BASE_URL
              value: "https://www.randomnumberapi.com"
